services:

  adoptions-image:
    image: adoptions-image
    container_name: adoptions-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - adoptions-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - adoptions-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  adoptions-network:
volumes:
  mysql-volume:

