version: '3.8'

services:
  jpa_adoptions:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/jpa_adoptions  # Cambié la URL para ser válida
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "123456"  # Contraseña vacía
    restart: always
    depends_on:
      docker-mysql:
        condition: service_healthy

  docker-mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: jpa_adoptions
      MYSQL_ROOT_PASSWORD: "123456"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10